// public/Js/tournaments/knockout-engine.js
// TrebleChasers ODL - Knockout Engine
// Defines TC knockout tournament types and creates brackets using bracket-engine.js

import {
  createKnockoutBracket,
  BRACKET_STATUS
} from "./bracket-engine.js";

export const KNOCKOUT_TYPES = {
  ELITE_CUP: "eliteCup",
  CHALLENGER_CUP: "challengerCup",
  DC_TOURNAMENT: "dcTournament",
  DC_MEMBERS_FRIDAY: "dcMembersFriday",
  ADMIN_KNOCKOUT: "adminKnockout"
};

export const KNOCKOUT_RULES = {
  eliteCup: {
    label: "Elite Cup",
    description: "Top 32 players from the live ELO table.",
    bracketSize: 32,
    format: "BO9",
    gameType: "501",
    lengthMode: "bestOf",
    target: 9,
    membersOnly: false,
    drawMode: "seeded",
    entrySource: "eloTop32",
    affectsElo: true,
    affectsTournamentLeaderboard: true,
    affectsProfiles: true,
    affectsCareerStats: true,
    autoGenerated: true,
    monthly: true
  },

  challengerCup: {
    label: "Challenger Cup",
    description: "Players ranked 33–64 from the live ELO table.",
    bracketSize: 32,
    format: "BO9",
    gameType: "501",
    lengthMode: "bestOf",
    target: 9,
    membersOnly: false,
    drawMode: "seeded",
    entrySource: "eloRank33To64",
    affectsElo: true,
    affectsTournamentLeaderboard: true,
    affectsProfiles: true,
    affectsCareerStats: true,
    autoGenerated: true,
    monthly: true
  },

  dcTournament: {
    label: "DC Tournament",
    description: "Open 32-player DartsCounter tournament.",
    bracketSize: 32,
    format: "BO9",
    gameType: "501",
    lengthMode: "bestOf",
    target: 9,
    membersOnly: false,
    drawMode: "random",
    entrySource: "registeredInterest",
    affectsElo: true,
    affectsTournamentLeaderboard: true,
    affectsProfiles: true,
    affectsCareerStats: true,
    autoGenerated: true,
    monthly: false
  },

  dcMembersFriday: {
    label: "Members Friday DC Tournament",
    description: "Members-only 32-player Friday DartsCounter tournament.",
    bracketSize: 32,
    format: "BO9",
    gameType: "501",
    lengthMode: "bestOf",
    target: 9,
    membersOnly: true,
    drawMode: "random",
    entrySource: "registeredInterestMembersOnly",
    affectsElo: true,
    affectsTournamentLeaderboard: true,
    affectsProfiles: true,
    affectsCareerStats: true,
    autoGenerated: true,
    monthly: false
  },

  adminKnockout: {
    label: "Admin Knockout",
    description: "Custom admin-created knockout tournament.",
    bracketSize: null,
    format: "BO9",
    gameType: "501",
    lengthMode: "bestOf",
    target: 9,
    membersOnly: false,
    drawMode: "random",
    entrySource: "manualAdminSelection",
    affectsElo: true,
    affectsTournamentLeaderboard: true,
    affectsProfiles: true,
    affectsCareerStats: true,
    autoGenerated: false,
    monthly: false
  }
};

export function getKnockoutRules(type) {
  const key = String(type || "").trim();

  if (!KNOCKOUT_RULES[key]) {
    throw new Error(`Unknown knockout type: ${type}`);
  }

  return KNOCKOUT_RULES[key];
}

export function isMembersOnlyKnockout(type) {
  return getKnockoutRules(type).membersOnly === true;
}

export function canAffectElo(type) {
  return getKnockoutRules(type).affectsElo === true;
}

export function canAffectTournamentLeaderboard(type) {
  return getKnockoutRules(type).affectsTournamentLeaderboard === true;
}

export function canAffectProfiles(type) {
  return getKnockoutRules(type).affectsProfiles === true;
}

export function canAffectCareerStats(type) {
  return getKnockoutRules(type).affectsCareerStats === true;
}

export function generateTournamentId(type, date = new Date()) {
  const safeType = String(type || "knockout")
    .replace(/[^a-zA-Z0-9]/g, "")
    .toLowerCase();

  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  const t = String(date.getTime()).slice(-6);

  return `${safeType}_${y}${m}${d}_${t}`;
}

export function normaliseEntryPlayer(player, index = 0) {
  return {
    id: player.id || player.uid || player.playerId || `player_${index + 1}`,
    name: player.name || player.displayName || `Player ${index + 1}`,
    division: player.division || null,
    average: Number(player.average ?? player.avg ?? player.trackedAverage ?? 0),
    elo: Number(player.elo ?? player.currentElo ?? 0),
    seed: player.seed ?? null,
    isMember:
      player.isMember === true ||
      player.member === true ||
      player.role === "member" ||
      player.role === "admin",
    role: player.role || "player"
  };
}

export function filterEligiblePlayers(players = [], type) {
  const rules = getKnockoutRules(type);

  const normalised = players.map(normaliseEntryPlayer);

  if (!rules.membersOnly) {
    return normalised;
  }

  return normalised.filter((player) => player.isMember === true);
}

export function sortByElo(players = []) {
  return [...players].sort((a, b) => {
    const eloA = Number(a.elo ?? 0);
    const eloB = Number(b.elo ?? 0);

    if (eloB !== eloA) return eloB - eloA;

    const avgA = Number(a.average ?? 0);
    const avgB = Number(b.average ?? 0);

    return avgB - avgA;
  });
}

export function selectEliteCupPlayers(players = []) {
  return sortByElo(players)
    .slice(0, 32)
    .map((player, index) => ({
      ...player,
      seed: index + 1
    }));
}

export function selectChallengerCupPlayers(players = []) {
  return sortByElo(players)
    .slice(32, 64)
    .map((player, index) => ({
      ...player,
      seed: index + 1
    }));
}

export function selectPlayersForKnockout(players = [], type) {
  const rules = getKnockoutRules(type);
  const eligible = filterEligiblePlayers(players, type);

  if (type === KNOCKOUT_TYPES.ELITE_CUP) {
    return selectEliteCupPlayers(eligible);
  }

  if (type === KNOCKOUT_TYPES.CHALLENGER_CUP) {
    return selectChallengerCupPlayers(eligible);
  }

  if (rules.bracketSize) {
    return eligible.slice(0, rules.bracketSize);
  }

  return eligible;
}

export function createKnockoutTournament({
  type,
  players = [],
  name = null,
  startsAt = null,
  createdBy = "system",
  bracketSize = null,
  metadata = {}
}) {
  const rules = getKnockoutRules(type);

  const selectedPlayers = selectPlayersForKnockout(players, type);

  const tournamentId =
    metadata.tournamentId ||
    generateTournamentId(type);

  const tournamentName =
    name ||
    rules.label;

  const finalBracketSize =
    bracketSize ||
    rules.bracketSize ||
    null;

  const bracket = createKnockoutBracket({
    tournamentId,
    name: tournamentName,
    players: selectedPlayers,
    mode: rules.drawMode,
    bracketSize: finalBracketSize,
    format: rules.format,
    startsAt,
    createdBy,
    metadata: {
      ...metadata,
      type,
      rules,
      affectsElo: rules.affectsElo,
      affectsTournamentLeaderboard: rules.affectsTournamentLeaderboard,
      affectsProfiles: rules.affectsProfiles,
      affectsCareerStats: rules.affectsCareerStats,
      membersOnly: rules.membersOnly,
      gameType: rules.gameType,
      lengthMode: rules.lengthMode,
      target: rules.target
    }
  });

  return {
    ...bracket,
    competitionType: type,
    rules,
    status: BRACKET_STATUS.LIVE
  };
}

export function createEliteCup(players = [], options = {}) {
  return createKnockoutTournament({
    type: KNOCKOUT_TYPES.ELITE_CUP,
    players,
    name: options.name || "Elite Cup",
    startsAt: options.startsAt || null,
    createdBy: options.createdBy || "system",
    metadata: options.metadata || {}
  });
}

export function createChallengerCup(players = [], options = {}) {
  return createKnockoutTournament({
    type: KNOCKOUT_TYPES.CHALLENGER_CUP,
    players,
    name: options.name || "Challenger Cup",
    startsAt: options.startsAt || null,
    createdBy: options.createdBy || "system",
    metadata: options.metadata || {}
  });
}

export function createDCTournament(players = [], options = {}) {
  return createKnockoutTournament({
    type: KNOCKOUT_TYPES.DC_TOURNAMENT,
    players,
    name: options.name || "DC Tournament",
    startsAt: options.startsAt || null,
    createdBy: options.createdBy || "admin",
    metadata: options.metadata || {}
  });
}

export function createMembersFridayDCTournament(players = [], options = {}) {
  return createKnockoutTournament({
    type: KNOCKOUT_TYPES.DC_MEMBERS_FRIDAY,
    players,
    name: options.name || "Members Friday DC Tournament",
    startsAt: options.startsAt || null,
    createdBy: options.createdBy || "admin",
    metadata: options.metadata || {}
  });
}

export function createAdminKnockout(players = [], options = {}) {
  return createKnockoutTournament({
    type: KNOCKOUT_TYPES.ADMIN_KNOCKOUT,
    players,
    name: options.name || "Admin Knockout",
    startsAt: options.startsAt || null,
    createdBy: options.createdBy || "admin",
    bracketSize: options.bracketSize || null,
    metadata: options.metadata || {}
  });
}

export function getKnockoutSummary(tournament) {
  const rules = tournament.rules || tournament.metadata?.rules || {};

  return {
    id: tournament.id,
    name: tournament.name,
    type: tournament.competitionType || tournament.metadata?.type,
    status: tournament.status,
    bracketSize: tournament.bracketSize,
    playerCount: tournament.playerCount,
    format: tournament.format,
    membersOnly: rules.membersOnly === true,
    affectsElo: rules.affectsElo === true,
    affectsTournamentLeaderboard: rules.affectsTournamentLeaderboard === true,
    affectsProfiles: rules.affectsProfiles === true,
    affectsCareerStats: rules.affectsCareerStats === true,
    startsAt: tournament.startsAt,
    champion: tournament.champion || null
  };
}